name: Terraform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform FMT
        run: terraform fmt -check

      - name: Terraform Init
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN_TF }}
          TF_VAR_github_owner: ${{ secrets.TF_GITHUB_OWNER }}
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN_TF }}
          TF_VAR_github_owner: ${{ secrets.TF_GITHUB_OWNER }}
        run: terraform plan -out=tfplan

      - name: Upload Plan Result
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        env:
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN_TF }}
          TF_VAR_github_owner: ${{ secrets.TF_GITHUB_OWNER }}
        run: terraform apply -auto-approve tfplan